config/routes.rb
Rails.application.routes.draw do
  
  root :to => 'users#new'
  
  resources :users, only: [:new, :create, :show, :destroy]
  resources :weights, only: [:new, :create]
  resources :welcome

  get 'sessions/new' => 'sessions#new'
  post 'sessions' => 'sessions#create'
  delete 'sessions' => 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base

  validates :username, presence: true, uniqueness: true
  has_secure_password
  
  has_many :weights

end

app/models/weight.rb
class Weight < ActiveRecord::Base

	belongs_to :user
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def authenticate
    redirect_to new_user_path unless session[:current_user_id]
  end

  def current_user
    User.find(session[:current_user_id]) if session[:current_user_id]
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:current_user_id] = user.id
      redirect_to new_weight_path
    else
      redirect_to root_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate, except: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:current_user_id] = @user.id
      redirect_to new_weight_path
    else
      redirect_to root_path
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    session[:current_user_id] = nil
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end


end

app/controllers/weights_controller.rb
class WeightsController < ApplicationController
  
  #needed for post route
  def new
  	@weight = Weight.new	
  end

  def create
  	#binding.pry
  	@weight = Weight.create({
  		weight: params[:weight][:wieght].to_f,
  		user_id: session[:current_user_id]
  		})
  	redirect_to new_weight_path 
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index	
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weights_helper.rb
module WeightsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Gainzilla</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  
	  <script src="https://maps.googleapis.com/maps/api/js?sensor=true"></script>
      <meta name="viewport" content="initial-scale=1.0">
      <meta charset="utf-8">
	  <!-- Latest compiled and minified CSS -->
	  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

	  <!-- Optional theme -->
	  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

	  <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
	  <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
	  <!-- Latest compiled and minified JavaScript -->
	  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

	  <%= csrf_meta_tags %>
	</head>

	<body>

		<div class="black-bg">
		  <!-- Nav bar -->
		  <div class="container hidden-xs no-gutter"> 
		    <div class="hidden-xs">
		      <nav class="navbar-default" role="navigation">
		        <div class="container">
		          <div class="zilla-logo">
		          <%= link_to href: '/' do %>
		              <%= image_tag 'zillaHead.png', width: 72, height: 72, alt: 'zillaHead'%>
		          <% end %>
		        </div>
		            <div class="zilla-login" id="nav-scroll-down">
					  <% if session[:current_user_id]%>
					  <%= link_to "#{User.find(session[:current_user_id]).username}", user_path(session[:current_user_id])%>
					  <%= link_to "Logout", sessions_path, method: :delete %>
					  <% else %>
		              <%= image_tag 'navbar_text.png', width: 300, height: 24, alt: 'navbar_text'%>
					  <% end %>
		            </div>
		      </nav>
		    </div>
		  </div>
		</div>

		<%= yield %>

	</body>

</html>

app/views/users/index.html.erb
<!-- Blank index -->

app/views/users/new.html.erb
<!-- main page splash page -->
<div class="black-bg">

  <div class="container hidden-xs no-gutter"> 
  <!--|____________| -->
    <div class="row no-gutter no-hugger">
      <div class="col-xs-12 text-center splash-bg no-gutter">
        <%= image_tag 'splash_img.png', alt: 'splash_img', id: "splash-bg-img"%>
      </div>
    </div>

    <div class='ground-color'></div>
    <div class="river-color"></div>
  </div>
  
  <div class="container hidden-xs no-gutter"> 
    <div class="row login-banner no-gutter no-hugger">
      <!--|______||______| -->
      <div class="col-xs-6 text-center no-gutter banner-text">
        <%= image_tag 'login_banner.png', alt: 'login_img'%>
      </div>
      <!--|______||______| -->
      <div class="col-xs-6 text-center no-gutter banner-text">
         <%= image_tag 'register_banner.png', alt: 'login_img'%>
      </div>
    </div>
  </div>

  <div class="container hidden-xs no-gutter crack-bg parent-div"> 
    <div class="login-bg">
    <!--|____________| -->
      <%= image_tag 'crack_bg.png', alt: 'crack_bg img', id: "crack-bg-img" %> 
    </div>
    <div class="login-form">

    <!--|______||______| -->
      <div class="col-xs-6 text-center no-gutter banner-text">
        <%= image_tag 'username_text.png', alt: 'username_text'%> 
        <div class="form-space"></div>
        <%= form_tag(sessions_path) do%> 
        <%= text_field_tag :username%><br>
          <div class="login-form"></div>
          <%= image_tag 'password_text.png', alt: 'password_text'%> 
          <div class="form-space"></div>
          <%= password_field_tag :password%><br>
          <div class="login-form">
            <%= image_tag 'go_button.png', alt: 'go_button img', class: "go-button" %> 
          </div>
          <%= submit_tag "", id: "go-button-submit" %>
        <% end %>
      </div>
    </div>
    <div class="register-form">
      <!--|______||______| -->
      <div class="col-xs-6 text-center no-gutter banner-text">
        <%= form_for @user do |f|%>
          <%= image_tag 'newuser_name.png', alt: 'newuser_name_text'%> 
          <div class="form-space"></div>
          <%= f.text_field :username %><br>
          <div class="login-form"></div>
          <%= image_tag 'password_text.png', alt: 'password_text'%><br>
          <div class="form-space"></div>
          <%= f.password_field :password%><br>
          <div class="login-form"></div>
          <%= image_tag 'password_again_text.png', alt: 'password_again_text'%><br>
          <div class="form-space"></div>
          <%= f.password_field :password_confirmation%><br>
          <div class="form-space">
          </div>
          <%= image_tag 'getin_button.png', alt: 'getin_button img', class: "getin-button"%>
        <br>
        <%= f.submit "", id: "getin-button-submit" %>
        <% end %>
      </div>
    </div>

  </div>

</div>

app/views/weights/new.html.erb
<script>
	function initialize() {
	    var latlng = new google.maps.LatLng(40.740112,-73.990060);
	        var myOptions ={
	            zoom: 12,
	            center: {lat: 40.740112, lng: -73.990060},
	           panControl: true,
	             zoomControl: true,
	             size: (860,490)
	           };        
	        var map = new google.maps.Map(document.getElementById('map'),myOptions);
	        var myLatLng = {lat: 40.740112, lng: -73.990060};

	        var infowindow = new google.maps.InfoWindow();
	            var latitude =  myLatLng.lat;
	            var longitude=  myLatLng.lng;
	        
	        var markersAryAry = [
	        	[40.718961, -73.987628],[40.708127, -74.004692],[40.749814,-73.983969],[40.709437,-74.009439],[40.716073,-74.005147],[40.726742,-73.985755],[40.730340, -74.000353],[40.729007, -73.993142],[40.737270, -73.991207],[40.737270, -73.996660],[40.745983, -73.990959],[40.750080, -73.992589],[40.750730, -73.986581],[40.750780, -73.986616],[40.754746, -73.988247]
	        ]
	        for (var e = 0; e < markersAryAry.length; e++) {
	        	var marker = new google.maps.Marker({
	            position: new google.maps.LatLng(markersAryAry[e][0], markersAryAry[e][1]),
	            map: map,
	            animation: google.maps.Animation.DROP
		        });
	        };
		};
	google.maps.event.addDomListener(window, "load", initialize);
</script>

<!-- weight page -->
<div class="black-bg">

  <div class="container hidden-xs no-gutter"> 
    <div class="row no-gutter no-hugger">
  	<!--|____________| -->
      <div class="col-xs-12 text-center splash-bg no-gutter">	
		<div class="weight-top-banner text-center">
			<%= image_tag 'please_enter.png', width: 490, height: 20, alt: 'enter_weight'%>
		</div>
		<div class="weight-scale-bg">
			<div class="scale">
				<!-- <form action="" id="weight-input">
					<input id="weight-box" size="8" type="password" name="weight">
				</form> -->
        <%= form_for @weight, html:{id: "weight-input" } do |f| %>
          <%= f.password_field :weight, {size: 8, class: "weight-input"} %>
          <%= f.submit "", class: "weight-submit" %>
        <% end %>
				<%= image_tag 'scale2.png', width: 280, height: 295, alt: 'scale_img'%>
			</div>
			<div id="check-box">
				<%= image_tag 'check.png', width: 158, height: 60, alt: 'scale_img'%>
			</div>
		</div>
	  </div>
	</div>

  <div class="container hidden-xs no-gutter"> 
	<div class="row no-gutter no-hugger chart-bg">
  	<!--|_||_____||_____||_| -->
  	  <div class="col-xs-1 weight-hide"></div>
  	  <div class="col-xs-5 text-center no-gutter parent-div weight-hide">
  	  	<div id="zilla-weight">
  	  		<%= image_tag 'zillaWeight.png', width: 250, height: 210, alt: 'zillaWeight_text'%>
  	  	</div>
  	  	<div id="everything-ok">
  	  		<%= image_tag 'everything_ok.png', width: 202, height: 115, alt: 'zillaWeight_text'%>
  	  	</div>
  	  	<div id="red-arrow-down">
  	  		<%= image_tag 'red_arrow_down.png', width: 108, height: 110, alt: 'red_arrow_down_img'%>
  	  	</div>
  	  </div>
  	  <div class="col-xs-5 text-center no-gutter weight-hide">	
		<div class="chart-canvas" >
			<canvas id="myChart" width="300" height="300"></canvas>
		</div>
		<div id="science-graph">
			<%= image_tag 'science_graph.png', width: 330, height: 20, alt: 'science_img'%>
		</div>
	  <div class="col-xs-1 weight-hide"></div>
  	  </div>
  	</div>

  <div class="container hidden-xs no-gutter"> 
	<div class="row no-gutter no-hugger chart-bg">
  	  <!--|____________| -->
  	  <div class="col-xs-12 text-center parent-div" id="zilla-eats-bg">
  	  	<div id="zilla-eat">
			<%= image_tag 'zilla_eats.png', width: 450, height: 320, alt: 'zilla_eats_img'%>
  	  	</div>
  	  	<div id="hungry">
			<%= image_tag 'hungry.png', width: 260, height: 50, alt: 'hurgry'%>
  	  	</div>
  	  	<div id="yellow-arrow-down">
  	  		<%= image_tag 'yellow_arrow_down.png', width: 108, height: 110, alt: 'yellow_arrow_down_img'%>
  	  	</div>
  	  </div>
  	</div>
  </div>

  <div class="container hidden-xs no-gutter map-bg">
  	<div class="row no-gutter no-hugger">
  		<div class="col-xs-2 no-gutter"></div>
  		<div class="col-xs-2 no-gutter">
	  	  	<div id="visit-mc">
	  	  		<%= image_tag 'visit.png', width: 185, height: 143, alt: 'visit_img'%>
	  	  	</div>
	  	</div>
	  	<div class="col-xs-2 no-gutter"></div>
	  	<div class="col-xs-2 no-gutter">
	  		<div id="visit-mc">
				<%= image_tag 'time_to_pay.png', width: 278, height: 143, alt: 'time_to_pay'%>
	  	  	</div>
	  	</div>
	</div>
	<div class="row no-gutter no-hugger">
  	  <!--|____________| -->
  	  <div class="col-xs-12 no-gutter parent-div">
  	  	<div id="white-arrow-down">
  	  		<%= image_tag 'white_arrow_down.png', width: 80, height: 80, alt: 'white_arrow_down_img'%>
  	  	</div>
	  	<div class="center-sides" id="map"></div>
  	  </div>
  	</div>
  </div>
	   
  <div class="container hidden-xs no-gutter restaurant-bg">
  	<div class="row no-gutter no-hugger">
  	  <!--|____________| -->
  	  <div class="col-xs-12 no-gutter parent-div text-center">
  	  	<div id="orange-arrow-down">
  	  		<%= image_tag 'orange_arrow_down.png', width: 80, height: 80, alt: 'orange-arrow-down_img'%>
  	  	</div>
  	  	<div id="remember">
  	  		<%= image_tag 'remember.png', width: 360, height: 60, alt: 'remember_text'%>
  	  	</div>
  	  </div>
  	</div>
  	<div class="row no-gutter no-hugger">
  		<!--|____||____||____| -->
  		<div class="col-xs-4 no-gutter text-center" id="fader1">
  			<%= image_tag 'chinese.png', width: 270, height: 270, alt: 'chinese_img'%>
  		</div>
  		<div class="col-xs-4 no-gutter text-center"  id="fader2">
  			<%= image_tag 'indian.png', width: 270, height: 270, alt: 'indian_img'%>
  		</div>
  		<div class="col-xs-4 no-gutter text-center"  id="fader3">
  			<%= image_tag 'pizza.png', width: 270, height: 270, alt: 'pizza_img'%>
  		</div>
	</div>
  	<div class="row no-gutter no-hugger">
  		<!--|____||____||____| -->
  		<div class="col-xs-4 no-gutter text-center"  id="fader4">
  			<div class="restaurant-text">
  				<%= image_tag 'general.png', width: 270, height: 130, alt: 'general_text'%>
  			</div>
  		</div>
  		<div class="col-xs-4 no-gutter text-center"  id="fader5">
  			<div class="restaurant-text">
  				<%= image_tag 'naan.png', width: 270, height: 130, alt: 'naan_text'%>
  			</div>
  		</div>
  		<div class="col-xs-4 no-gutter text-center"  id="fader6">
  			<div class="restaurant-text">
  				<%= image_tag 'weak.png', width: 270, height: 130, alt: 'weak_text'%>
  			</div>
  		</div>
	</div>
  </div>

  <div class="container hidden-xs no-gutter end-bg">
  	<div class="row no-gutter no-hugger">
  	<!--|____________| -->
  	  <div class="col-xs-12 no-gutter parent-div text-center">
  	  	<div id="dark-arrow-down">
  	  		<%= image_tag 'dark_arrow_down.png', width: 110, height: 110, alt: 'dark_arrow_img'%>
  	  	</div>
  	  	<div id="be-ok">
  	  		<%= image_tag 'be_ok.png', width: 590, height: 113, alt: 'be_ok_img'%>
  	  	</div>
  	  </div>
  	</div>
  </div>


</div>

app/views/welcome/index.html.erb
<script>
	function initialize() {
	    var latlng = new google.maps.LatLng(40.740112,-73.990060);
	        var myOptions ={
	            zoom: 12,
	            center: {lat: 40.740112, lng: -73.990060},
	           panControl: true,
	             zoomControl: true,
	             size: (860,490)
	           };        
	        var map = new google.maps.Map(document.getElementById('map'),myOptions);
	        var myLatLng = {lat: 40.740112, lng: -73.990060};

	        var infowindow = new google.maps.InfoWindow();
	            var latitude =  myLatLng.lat;
	            var longitude=  myLatLng.lng;
	        
	        var markersAryAry = [
	        	[40.718961, -73.987628],[40.708127, -74.004692],[40.749814,-73.983969],[40.709437,-74.009439],[40.716073,-74.005147],[40.726742,-73.985755],[40.730340, -74.000353],[40.729007, -73.993142],[40.737270, -73.991207],[40.737270, -73.996660],[40.745983, -73.990959],[40.750080, -73.992589],[40.750730, -73.986581],[40.750780, -73.986616],[40.754746, -73.988247]
	        ]
	        for (var e = 0; e < markersAryAry.length; e++) {
	        	var marker = new google.maps.Marker({
	            position: new google.maps.LatLng(markersAryAry[e][0], markersAryAry[e][1]),
	            map: map,
	            animation: google.maps.Animation.DROP
		        });
	        };
		};
	google.maps.event.addDomListener(window, "load", initialize);
</script>

<!-- weight page -->
<div class="black-bg">

  <div class="container hidden-xs no-gutter"> 
    <div class="row no-gutter no-hugger">
  	<!--|____________| -->
      <div class="col-xs-12 text-center splash-bg no-gutter">	
		<div class="weight-top-banner text-center">
			<%= image_tag 'please_enter.png', width: 490, height: 20, alt: 'enter_weight'%>
		</div>
		<div class="weight-scale-bg">
			<div class="scale">
				<form action="" id="weight-input">
					<input id="weight-box" size="8" type="password" name="weight">
				</form>
				<%= image_tag 'scale2.png', width: 280, height: 295, alt: 'scale_img'%>
			</div>
			<div id="check-box">
				<%= image_tag 'check.png', width: 158, height: 60, alt: 'scale_img'%>
			</div>
		</div>
	  </div>
	</div>

  <div class="container hidden-xs no-gutter"> 
	<div class="row no-gutter no-hugger chart-bg">
  	<!--|_||_____||_____||_| -->
  	  <div class="col-xs-1 weight-hide"></div>
  	  <div class="col-xs-5 text-center no-gutter parent-div weight-hide">
  	  	<div id="zilla-weight">
  	  		<%= image_tag 'zillaWeight.png', width: 250, height: 210, alt: 'zillaWeight_text'%>
  	  	</div>
  	  	<div id="everything-ok">
  	  		<%= image_tag 'everything_ok.png', width: 202, height: 115, alt: 'zillaWeight_text'%>
  	  	</div>
  	  	<div id="red-arrow-down">
  	  		<%= image_tag 'red_arrow_down.png', width: 108, height: 110, alt: 'red_arrow_down_img'%>
  	  	</div>
  	  </div>
  	  <div class="col-xs-5 text-center no-gutter weight-hide">	
		<div class="chart-canvas" >
			<canvas id="myChart" width="300" height="300"></canvas>
		</div>
		<div id="science-graph">
			<%= image_tag 'science_graph.png', width: 330, height: 20, alt: 'science_img'%>
		</div>
	  <div class="col-xs-1 weight-hide"></div>
  	  </div>
  	</div>

  <div class="container hidden-xs no-gutter"> 
	<div class="row no-gutter no-hugger chart-bg">
  	  <!--|____________| -->
  	  <div class="col-xs-12 text-center parent-div" id="zilla-eats-bg">
  	  	<div id="zilla-eat">
			<%= image_tag 'zilla_eats.png', width: 450, height: 320, alt: 'zilla_eats_img'%>
  	  	</div>
  	  	<div id="hungry">
			<%= image_tag 'hungry.png', width: 260, height: 50, alt: 'hurgry'%>
  	  	</div>
  	  	<div id="yellow-arrow-down">
  	  		<%= image_tag 'yellow_arrow_down.png', width: 108, height: 110, alt: 'yellow_arrow_down_img'%>
  	  	</div>
  	  </div>
  	</div>
  </div>

  <div class="container hidden-xs no-gutter map-bg">
  	<div class="row no-gutter no-hugger">
  		<div class="col-xs-2 no-gutter"></div>
  		<div class="col-xs-2 no-gutter">
	  	  	<div id="visit-mc">
	  	  		<%= image_tag 'visit.png', width: 185, height: 143, alt: 'visit_img'%>
	  	  	</div>
	  	</div>
	  	<div class="col-xs-2 no-gutter"></div>
	  	<div class="col-xs-2 no-gutter">
	  		<div id="visit-mc">
				<%= image_tag 'time_to_pay.png', width: 278, height: 143, alt: 'time_to_pay'%>
	  	  	</div>
	  	</div>
	</div>
	<div class="row no-gutter no-hugger">
  	  <!--|____________| -->
  	  <div class="col-xs-12 no-gutter parent-div">
  	  	<div id="white-arrow-down">
  	  		<%= image_tag 'white_arrow_down.png', width: 80, height: 80, alt: 'white_arrow_down_img'%>
  	  	</div>
	  	<div class="center-sides" id="map"></div>
  	  </div>
  	</div>
  </div>
	   
  <div class="container hidden-xs no-gutter restaurant-bg">
  	<div class="row no-gutter no-hugger">
  	  <!--|____________| -->
  	  <div class="col-xs-12 no-gutter parent-div text-center">
  	  	<div id="orange-arrow-down">
  	  		<%= image_tag 'orange_arrow_down.png', width: 80, height: 80, alt: 'orange-arrow-down_img'%>
  	  	</div>
  	  	<div id="remember">
  	  		<%= image_tag 'remember.png', width: 360, height: 60, alt: 'remember_text'%>
  	  	</div>
  	  </div>
  	</div>
  	<div class="row no-gutter no-hugger">
  		<!--|____||____||____| -->
  		<div class="col-xs-4 no-gutter text-center" id="fader1">
  			<%= image_tag 'chinese.png', width: 270, height: 270, alt: 'chinese_img'%>
  		</div>
  		<div class="col-xs-4 no-gutter text-center"  id="fader2">
  			<%= image_tag 'indian.png', width: 270, height: 270, alt: 'indian_img'%>
  		</div>
  		<div class="col-xs-4 no-gutter text-center"  id="fader3">
  			<%= image_tag 'pizza.png', width: 270, height: 270, alt: 'pizza_img'%>
  		</div>
	</div>
  	<div class="row no-gutter no-hugger">
  		<!--|____||____||____| -->
  		<div class="col-xs-4 no-gutter text-center"  id="fader4">
  			<div class="restaurant-text">
  				<%= image_tag 'general.png', width: 270, height: 130, alt: 'general_text'%>
  			</div>
  		</div>
  		<div class="col-xs-4 no-gutter text-center"  id="fader5">
  			<div class="restaurant-text">
  				<%= image_tag 'naan.png', width: 270, height: 130, alt: 'naan_text'%>
  			</div>
  		</div>
  		<div class="col-xs-4 no-gutter text-center"  id="fader6">
  			<div class="restaurant-text">
  				<%= image_tag 'weak.png', width: 270, height: 130, alt: 'weak_text'%>
  			</div>
  		</div>
	</div>
  </div>

  <div class="container hidden-xs no-gutter end-bg">
  	<div class="row no-gutter no-hugger">
  	<!--|____________| -->
  	  <div class="col-xs-12 no-gutter parent-div text-center">
  	  	<div id="dark-arrow-down">
  	  		<%= image_tag 'dark_arrow_down.png', width: 110, height: 110, alt: 'dark_arrow_img'%>
  	  	</div>
  	  	<div id="be-ok">
  	  		<%= image_tag 'be_ok.png', width: 590, height: 113, alt: 'be_ok_img'%>
  	  	</div>
  	  </div>
  	</div>
  </div>


</div>